### ISSUE TITLE
Build new images after PR

### ISSUE THREAD

**Issue by orelgueta** [gammasim/containers#47]
I think that in one of the last PRs you made it such that we build new images manually by clicking a button. The issue is that we "forgot" and are still using the conda based images in our simtools tests. As a result, we didn't realise that zstd is not installed and the containers can't actually run sim_telarray. I will fix the zstd issue, but I suggest that perhaps we build new images when a PR is merged.

**Comment by GernotMaier** [comment]
Images are still build for pull requests, releases, new version tags (starting with `v`) and every Sunday night, see here https://github.com/gammasim/containers/blob/48bfaae5c7b3b599f6261d11ade8b207a1f9d030/.github/workflows/build-image.yml#L4

So this didn't change. The issue is that what we need is to build images after pull requests in simtools. To my knowledge we cannot trigger a workflow here on an event in another repository (simtools). 

I think we should discuss to move the docker files to simtools. It would add  a docker directory with three docker files, a readme, and a github workflow (which then we do not need to trigger manually). I would favor this solution.

**Comment by orelgueta** [comment]
I didn't mean a PR in simtools, but a PR here (I was aware of the simtools PR issue).

Either way, now I do see an updated container when I tried so something happened in the meantime. Either it wasn't built with the previous PR or perhaps I had a cached version of the containers on my system and when I ran them, despite pointing to the "latest" one, I got the cached version. It doesn't matter, this issue is essentially solved. I will therefore close this issue. We should discuss moving the containers into simtools, but probably better in a separate issue or in person.
